# Generated by Django 4.0.10 on 2023-04-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
